version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/potgressql/data

volumes:
  postgres_data:
    
    
